#!/usr/bin/env bash
#
# Generates .github/workflows/ci.yml — lint the contract once, migrate the
# database once, then lint/typecheck/test every one of the 22 services as a
# matrix job. A matrix instead of one long sequential job for two reasons:
# a failure in one service doesn't hide whether the other 21 would have
# passed, and the whole suite runs in parallel instead of one at a time.
#
# Run from the repo root:
#   bash setup-ci.sh
#
set -euo pipefail

ROOT="$(pwd)"
[ -f "$ROOT/pnpm-workspace.yaml" ] || { echo "Run this from the repo root."; exit 1; }

mkdir -p "$ROOT/.github/workflows"

python3 - "$ROOT/.github/workflows/ci.yml" << 'PY'
import sys

path = sys.argv[1]

SERVICES = [
    "auth", "patient", "doctor", "appointment", "consultation", "messaging",
    "followup", "notification", "ai", "emergency", "pharmacy", "payment",
    "diagnostics", "quality", "families", "education", "network", "insurance",
    "research", "surveillance", "gateway", "sync", "devices", "prevention", "facilities",
]

matrix_list = "\n".join(f"          - {s}" for s in SERVICES)

content = f"""# Generated by setup-ci.sh — regenerate rather than hand-edit the service
# list; it lives in that script so it can never quietly drift from the repo.
name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  DATABASE_URL: postgresql://ahealth:ahealth@localhost:5432/ahealth_dev?schema=public
  JWT_SECRET: ci-test-secret-32-characters-minimum-000
  JWT_ISSUER: a-health
  JWT_AUDIENCE: a-health-api

jobs:
  contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter @a-health/api lint
      - run: pnpm --filter @a-health/api generate

  migrate:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: ahealth
          POSTGRES_PASSWORD: ahealth
          POSTGRES_DB: ahealth_dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ahealth -d ahealth_dev"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter @a-health/database exec prisma migrate deploy

  service:
    needs: [contract, migrate]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
{matrix_list}
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: ahealth
          POSTGRES_PASSWORD: ahealth
          POSTGRES_DB: ahealth_dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ahealth -d ahealth_dev"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter @a-health/database exec prisma migrate deploy
      - name: Typecheck
        run: pnpm --filter @a-health/${{{{ matrix.service }}}} exec tsc --noEmit
      - name: Test
        run: pnpm --filter @a-health/${{{{ matrix.service }}}} test
"""

open(path, "w").write(content)
print(f"  .github/workflows/ci.yml written — {len(SERVICES)} services in the matrix")
PY

python3 - "$ROOT/.github/workflows/ci.yml" << 'PY'
import sys, yaml
d = yaml.safe_load(open(sys.argv[1]))
jobs = d.get("jobs", {})
print(f"  parsed OK: jobs = {list(jobs.keys())}")
services_in_matrix = jobs["service"]["strategy"]["matrix"]["service"]
print(f"  matrix service count: {len(services_in_matrix)}")
dupes = {s for s in services_in_matrix if services_in_matrix.count(s) > 1}
print(f"  duplicate matrix entries: {dupes or 'none'}")
if dupes:
    sys.exit(1)
PY

echo
echo "Done. Commit and push .github/workflows/ci.yml to activate it on GitHub."
