# syntax=docker/dockerfile:1.7

FROM node:22-slim AS build

RUN apt-get update \
	&& apt-get install -y --no-install-recommends openssl ca-certificates \
	&& rm -rf /var/lib/apt/lists/* \
	&& corepack enable
WORKDIR /repo

ARG APP_NAME
ARG APP_DIR

COPY pnpm-workspace.yaml package.json pnpm-lock.yaml turbo.json ./
COPY apps ./apps
COPY packages ./packages
COPY services ./services

RUN --mount=type=cache,id=a-health-pnpm-store,target=/pnpm/store \
	pnpm config set store-dir /pnpm/store && \
	pnpm install --frozen-lockfile
RUN pnpm --filter "${APP_NAME}" build

FROM node:22-slim AS runtime

ARG APP_NAME
ARG APP_DIR
RUN corepack enable
ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV APP_DIR=${APP_DIR}
ENV APP_NAME=${APP_NAME}

WORKDIR /repo
COPY --from=build /repo ./

EXPOSE 3000
CMD ["sh", "-c", "pnpm --filter \"${APP_NAME}\" start"]
