packages:
  - "apps/*"
  - "packages/*"
  - "services/*"
ignoredBuiltDependencies:
  - '@prisma/client'
  - bcrypt
  - esbuild
  - prisma

onlyBuiltDependencies:
  - '@prisma/engines'
  - sharp
  - unrs-resolver
