#!/usr/bin/env bash
#
# Generates docker-compose.dev.yml and a shared dev Dockerfile for all 22
# services. Generated from the port map by a script, not hand-typed block by
# block — the same reasoning that made every schema/contract patch anchor on
# structure instead of literal text: 22 near-identical blocks is exactly
# where a manual copy-paste mistake hides.
#
# Postgres runs INSIDE compose here, replacing the manually-started
# ahealth-pg container (same db/user/password, so existing local data under
# that container is unaffected if you keep running it separately instead).
#
# Run from the repo root:
#   bash setup-docker-compose.sh
#
set -euo pipefail

ROOT="$(pwd)"
[ -f "$ROOT/pnpm-workspace.yaml" ] || { echo "Run this from the repo root."; exit 1; }

# syntax=docker/dockerfile:1.7

# Shared dev image for every service. Not a production image: installs the
# whole workspace and runs tsx directly for fast iteration, rather than a
# per-service multi-stage build. One Dockerfile, twenty-two services — the
# same "one implementation" principle applied to build tooling.
FROM node:22-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends openssl ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && corepack enable

WORKDIR /repo
COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./
COPY packages ./packages
COPY services ./services
COPY apps ./apps

RUN --mount=type=cache,id=a-health-pnpm-store,target=/pnpm/store \
    pnpm config set store-dir /pnpm/store && \
    pnpm install --frozen-lockfile
RUN pnpm --filter @a-health/database generate

CMD ["node", "--version"]
DOCKERFILE
echo "  Dockerfile.dev written"

python3 - "$ROOT/docker-compose.dev.yml" << 'PY'
import sys

path = sys.argv[1]

# name -> port. Generated from the same assignments recorded as each
# service shipped, not retyped by hand.
SERVICES = {
    "auth": 4001, "patient": 4002, "doctor": 4003, "appointment": 4004,
    "consultation": 4005, "messaging": 4006, "followup": 4007, "notification": 4008,
    "ai": 4009, "emergency": 4010, "pharmacy": 4011, "payment": 4012,
    "diagnostics": 4013, "quality": 4014, "families": 4015, "education": 4016,
    "network": 4017, "insurance": 4018, "research": 4019, "surveillance": 4020,
    "gateway": 4021, "sync": 4022, "devices": 4023, "prevention": 4024, "facilities": 4025,
}

# Services with extra env vars beyond the common set, keyed by service name.
EXTRA_ENV = {
    "gateway": [
        "GATEWAY_SHARED_SECRET=dev-gateway-secret-change-me",
        "CONSULTATION_SERVICE_URL=http://consultation:4005",
        "MESSAGING_SERVICE_URL=http://messaging:4006",
        "FOLLOWUP_SERVICE_URL=http://followup:4007",
    ],
    "sync": [
        "CONSULTATION_SERVICE_URL=http://consultation:4005",
        "MESSAGING_SERVICE_URL=http://messaging:4006",
        "FOLLOWUP_SERVICE_URL=http://followup:4007",
        "APPOINTMENT_SERVICE_URL=http://appointment:4004",
    ],
}

lines = []
lines.append("# Generated by setup-docker-compose.sh — regenerate rather than hand-edit")
lines.append("# service blocks; the port map and any per-service env additions live in")
lines.append("# that script, not here, so the two can never quietly drift apart.")
lines.append("name: a-health-dev")
lines.append("")
lines.append("services:")
lines.append("  postgres:")
lines.append("    image: postgres:16")
lines.append("    restart: unless-stopped")
lines.append("    environment:")
lines.append("      POSTGRES_USER: ahealth")
lines.append("      POSTGRES_PASSWORD: ahealth")
lines.append("      POSTGRES_DB: ahealth_dev")
lines.append("    ports:")
lines.append('      - "5432:5432"')
lines.append("    volumes:")
lines.append("      - ahealth_pg_data:/var/lib/postgresql/data")
lines.append("    healthcheck:")
lines.append('      test: ["CMD-SHELL", "pg_isready -U ahealth -d ahealth_dev"]')
lines.append("      interval: 5s")
lines.append("      timeout: 5s")
lines.append("      retries: 10")
lines.append("")

for name, port in SERVICES.items():
    lines.append(f"  {name}:")
    lines.append("    build:")
    lines.append("      context: .")
    lines.append("      dockerfile: Dockerfile.dev")
    lines.append(f'    command: ["node", "--import", "tsx", "src/index.ts"]')
    lines.append(f"    working_dir: /repo/services/{name}")
    lines.append("    depends_on:")
    lines.append("      postgres:")
    lines.append("        condition: service_healthy")
    lines.append("    environment:")
    lines.append("      NODE_ENV: development")
    lines.append(f"      PORT: {port}")
    lines.append("      DATABASE_URL: postgresql://ahealth:ahealth@postgres:5432/ahealth_dev?schema=public")
    lines.append("      JWT_SECRET: ${JWT_SECRET:-dev-secret-change-me-32-characters-minimum}")
    lines.append("      JWT_ISSUER: a-health")
    lines.append("      JWT_AUDIENCE: a-health-api")
    for extra in EXTRA_ENV.get(name, []):
        key = extra.split("=", 1)[0]
        val = extra.split("=", 1)[1]
        lines.append(f"      {key}: {val}")
    lines.append("    ports:")
    lines.append(f'      - "{port}:{port}"')
    lines.append("    volumes:")
    lines.append("      - ./services:/repo/services")
    lines.append("      - ./packages:/repo/packages")
    lines.append("")

lines.append("volumes:")
lines.append("  ahealth_pg_data:")

open(path, "w").write("\n".join(lines) + "\n")
print(f"  docker-compose.dev.yml written — {len(SERVICES)} services + postgres")
PY

python3 - "$ROOT/docker-compose.dev.yml" << 'PY'
import sys, yaml
d = yaml.safe_load(open(sys.argv[1]))
services = d["services"]
print(f"  parsed OK: {len(services)} services (including postgres)")
ports = [s["ports"][0] for name, s in services.items() if "ports" in s]
dupes = {p for p in ports if ports.count(p) > 1}
print(f"  duplicate port mappings: {dupes or 'none'}")
if dupes:
    sys.exit(1)
PY

echo
echo "Next:"
echo "  docker compose -f docker-compose.dev.yml up -d postgres"
echo "  pnpm --filter @a-health/database exec prisma migrate deploy"
echo "  docker compose -f docker-compose.dev.yml up --build"
